# GENERATED by scripts/generate-version.js -- do not edit.
# Regenerate with `pnpm run version:sync`; `pnpm run build` does it for you.
#
# hatchling reads this file too -- pyproject.toml declares `dynamic = ["version"]`
# and points [tool.hatch.version] here -- so the package metadata and
# `ble_bridge.__version__` cannot disagree.
VERSION = "0.15.0"
