#!/usr/bin/env node
/**
 * Write src/version.ts from package.json.
 *
 * The generated file is COMMITTED, not gitignored, because vitest and `tsc`
 * both compile src/ straight from the tree -- a fresh clone that had to run a
 * generator before it could typecheck would be a worse trap than the one this
 * replaces. tests/unit/version.test.ts is what keeps the committed copy honest.
 *
 * Runs as part of `pnpm run build`, so a release cannot ship a stale constant
 * even if someone bumps the version and forgets `pnpm run version:sync`.
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(projectRoot, 'package.json'), 'utf8'));

const contents = `// GENERATED by scripts/generate-version.js -- do not edit.
// Regenerate with \`pnpm run version:sync\`; \`pnpm run build\` does it for you.
//
// This is the single source of the \`_mv\` marker the client stamps onto its
// connect URL. It used to have two: an esbuild define for the browser bundle and
// a synchronous readFileSync of package.json for everything else, chosen by a
// \`typeof __PACKAGE_VERSION__\` conditional at runtime. That made \`_mv\` depend on
// how the package was built, and it dragged \`fs\` onto the connect path of every
// non-bundled entry point -- which is what stopped the ESM entry working in a
// browser bundler.
export const VERSION = '${version}';
`;

const target = join(projectRoot, 'src/version.ts');
writeFileSync(target, contents);
console.log(`✅ src/version.ts <- package.json (v${version})`);

// The Python service takes the same version from the same place. It used to carry
// its own literal, permanently "0.1.0" through the entire replatform, so
// `status.version` reported the same string for today's code and for six-month-old
// code. The mock and the service ship as one release; one release has one version.
//
// Committed for the same reason src/version.ts is: a fresh clone that had to run a
// Node generator before Python could import would be a worse trap than the one this
// replaces. bridge/tests/test_version.py is what keeps the copy honest.
const pyContents = `# GENERATED by scripts/generate-version.js -- do not edit.
# Regenerate with \`pnpm run version:sync\`; \`pnpm run build\` does it for you.
#
# hatchling reads this file too -- pyproject.toml declares \`dynamic = ["version"]\`
# and points [tool.hatch.version] here -- so the package metadata and
# \`ble_bridge.__version__\` cannot disagree.
VERSION = "${version}"
`;
const pyTarget = join(projectRoot, 'bridge/src/ble_bridge/_version.py');
writeFileSync(pyTarget, pyContents);
console.log(`✅ bridge/src/ble_bridge/_version.py <- package.json (v${version})`);
