#!/usr/bin/env node
/**
 * Write src/version.ts from package.json.
 *
 * The generated file is COMMITTED, not gitignored, because vitest and `tsc`
 * both compile src/ straight from the tree -- a fresh clone that had to run a
 * generator before it could typecheck would be a worse trap than the one this
 * replaces. tests/unit/version.test.ts is what keeps the committed copy honest.
 *
 * Runs as part of `pnpm run build`, so a release cannot ship a stale constant
 * even if someone bumps the version and forgets `pnpm run version:sync`.
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(projectRoot, 'package.json'), 'utf8'));

const contents = `// GENERATED by scripts/generate-version.js -- do not edit.
// Regenerate with \`pnpm run version:sync\`; \`pnpm run build\` does it for you.
//
// This is the single source of the \`_mv\` marker the client stamps onto its
// connect URL. It used to have two: an esbuild define for the browser bundle and
// a synchronous readFileSync of package.json for everything else, chosen by a
// \`typeof __PACKAGE_VERSION__\` conditional at runtime. That made \`_mv\` depend on
// how the package was built, and it dragged \`fs\` onto the connect path of every
// non-bundled entry point -- which is what stopped the ESM entry working in a
// browser bundler.
export const VERSION = '${version}';
`;

const target = join(projectRoot, 'src/version.ts');
writeFileSync(target, contents);
console.log(`✅ src/version.ts <- package.json (v${version})`);
