// GENERATED by scripts/generate-version.js -- do not edit.
// Regenerate with `pnpm run version:sync`; `pnpm run build` does it for you.
//
// This is the single source of the `_mv` marker the client stamps onto its
// connect URL. It used to have two: an esbuild define for the browser bundle and
// a synchronous readFileSync of package.json for everything else, chosen by a
// `typeof __PACKAGE_VERSION__` conditional at runtime. That made `_mv` depend on
// how the package was built, and it dragged `fs` onto the connect path of every
// non-bundled entry point -- which is what stopped the ESM entry working in a
// browser bundler.
export const VERSION = '0.8.0';
